# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1f2613e56f9685d296c6cc195188829315f58b9b2c53260eb74f9388ce9eaf73e8f22171ec74088bd146b1961dfe587298af24cb41adc77e172970b63878a6c4

test:
  secret_key_base: 9ca4fd0e5b3e663fc5de91076522e25bdc856552289dbbfeb965ea2c17b098a2269d2aea9e04efddcc07b079894d47f2e48c71681a46e42912fa77eb20f09fbb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
